# ── TechNexus Lab Static Inventory ────────────────────────────────────────

[ctrl]
ctrl.technexus.com ansible_host=192.168.4.102

[execution_nodes]
exec1.technexus.com ansible_host=192.168.4.103
exec2.technexus.com ansible_host=192.168.4.104

[hub]
hub.technexus.com ansible_host=192.168.4.105

[eda]
eda.technexus.com ansible_host=192.168.4.106

[gateway]
gate.technexus.com ansible_host=192.168.4.107

[monitoring]
mnt.technexus.com ansible_host=192.168.4.108

[jenkins]
jenkins.technexus.com ansible_host=192.168.4.109

[aap:children]
ctrl
execution_nodes
hub
eda
gateway

[lab:children]
aap
monitoring
jenkins

[all:vars]
ansible_user=ansible_aap
ansible_ssh_private_key_file=/home/ansible_aap/.ssh/id_ed25519
ansible_become=true
ansible_become_method=sudo

[proxmox_host]
technexus ansible_host=192.168.4.50 ansible_user=root
