- name: Retrieve and save execution environment details to CSV
  hosts: localhost
  gather_facts: no
  vars:
    awx_api_url: "http://192.168.4.100"
    awx_api_token: # Provide your AWX API token here
    execution_env_csv_file_path: "/tmp/execution_environments_report.csv"
  tasks:
    - name: Fetch execution environments from AWX
      ansible.builtin.uri:
        url: "{{ awx_api_url }}/api/v2/execution_environments/"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Accept: "application/json"
        return_content: yes
        validate_certs: no
      register: execution_environments_response

    - name: Parse execution environment details
      ansible.builtin.set_fact:
        execution_environments_data: "{{ execution_environments_response.json.results }}"

    - name: Create empty CSV file for execution environments report
      ansible.builtin.file:
        path: "{{ execution_env_csv_file_path }}"
        state: touch

    - name: Create CSV file header for execution environments report
      ansible.builtin.copy:
        content: "Name,Collections,Python Libraries,Other Components,Inheritance\n"
        dest: "{{ execution_env_csv_file_path }}"
        force: yes

    - name: Fetch details for each execution environment
      ansible.builtin.uri:
        url: "{{ item.url }}"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Accept: "application/json"
        return_content: yes
        validate_certs: no
      loop: "{{ execution_environments_data }}"
      register: execution_environment_details

    - name: Parse details for each execution environment
      ansible.builtin.set_fact:
        execution_environments_with_details: >
          {{
            execution_environment_details.results | map(attribute='json') | list
          }}

    - name: Append execution environment details to CSV
      ansible.builtin.lineinfile:
        path: "{{ execution_env_csv_file_path }}"
        line: >
          {{
            (item.name | default('N/A') | string) + "," +
            (item.collections | default('N/A') | string) + "," +
            (item.python_libraries | default('N/A') | string) + "," +
            (item.other_components | default('N/A') | string) + "," +
            (item.inheritance | default('N/A') | string)
          }}
        state: present
        create: yes
      loop: "{{ execution_environments_with_details }}"

    - name: Display content of the execution environments report CSV file
      ansible.builtin.shell: "cat {{ execution_env_csv_file_path }}"
      register: execution_env_csv_file_content

    - name: Show execution environments report CSV file content
      ansible.builtin.debug:
        msg: "{{ execution_env_csv_file_content.stdout }}"
