- name: Query Ansible Automation Platform API
  hosts: mycontrol
  gather_facts: no
  vars:
    api_url: "http://mycontrol/api/v2/jobs/"
    api_token: "AFVwEe3kUl2fiK3LsK5qGnSMejWTon"
  tasks:
    - name: Get list of jobs
      uri:
        url: "{{ api_url }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        return_content: yes
      register: api_response

    - name: Show API response
      debug:
        var: api_response.json

