---
- name: Ensure all teams have access to Ansible Utility Processes organization
  hosts: localhost
  gather_facts: no
  vars:
    awx_api_url: "http://192.168.4.100"
    awx_api_token: # Provide your AWX API token here
    target_org: "Ansible Utility Processes"
    permissions: ["execute", "read"]
  tasks:
    - name: Fetch all organizations from AWX
      ansible.builtin.uri:
        url: "{{ awx_api_url }}/api/v2/organizations/"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Accept: "application/json"
        return_content: yes
        validate_certs: no
      register: organizations_response

    - name: Parse organization details
      ansible.builtin.set_fact:
        organizations_data: "{{ organizations_response.json.results }}"

    - name: Fetch all teams for each organization
      ansible.builtin.uri:
        url: "{{ awx_api_url }}/api/v2/teams/?organization={{ item.id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Accept: "application/json"
        return_content: yes
        validate_certs: no
      register: teams_response
      loop: "{{ organizations_data }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Parse teams details
      ansible.builtin.set_fact:
        teams_data: "{{ teams_response.json.results }}"

    - name: Fetch the ID of the Ansible Utility Processes organization
      ansible.builtin.uri:
        url: "{{ awx_api_url }}/api/v2/organizations/?name={{ target_org }}"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Accept: "application/json"
        return_content: yes
        validate_certs: no
      register: target_org_response

    - name: Set target organization ID
      ansible.builtin.set_fact:
        target_org_id: "{{ target_org_response.json.results[0].id }}"

    - name: Grant Execute and Read permissions to each team
      ansible.builtin.uri:
        url: "{{ awx_api_url }}/api/v2/teams/{{ item.id }}/roles/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body: >
          {
            "id": {{ target_org_id }},
            "type": "organization",
            "roles": ["{{ permissions | join('", "')}}"]
          }
        status_code: [200, 201, 204]
      loop: "{{ teams_data }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Display success message
      ansible.builtin.debug:
        msg: "All teams have been granted Execute and Read permissions to the Ansible Utility Processes organization"
