---
- name: Assign Permissions to AWX Teams for Ansible Utility Processes
  hosts: localhost
  gather_facts: no
  vars:
    awx_url: "https:/192.168.4.100/api/v2"
    awx_token: 
    org_name: "Ansible Utility Processes"
    permissions:
      - execute
      - read

  tasks:
    - name: Get list of organizations
      uri:
        url: "{{ awx_url }}/organizations/"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_token }}"
        return_content: yes
      register: organizations

    - name: Find the ID of the Ansible Utility Processes organization
      set_fact:
        utility_org_id: "{{ organizations.json.results | selectattr('name', 'equalto', org_name) | map(attribute='id') | first }}"

    - name: Get list of teams for the organization
      uri:
        url: "{{ awx_url }}/organizations/{{ utility_org_id }}/teams/"
        method: GET
        headers:
          Authorization: "Bearer {{ awx_token }}"
        return_content: yes
      register: teams

    - name: Assign permissions to teams
      uri:
        url: "{{ awx_url }}/teams/{{ item.id }}/permissions/"
        method: POST
        headers:
          Authorization: "Bearer {{ awx_token }}"
        body:
          permissions:
            - name: "execute"
            - name: "read"
        body_format: json
      loop: "{{ teams.json.results }}"
      loop_control:
        label: "{{ item.name }}"
      register: permissions_assigned

    - name: Debug: Show the assigned permissions for each team
      debug:
        msg: "Assigned permissions for team: {{ item.name }}"
      loop: "{{ permissions_assigned.results }}"
