---
- name: Install httpd, mariadb, dhcpd, @Development tools and update the systems
  hosts: test, webservers
  become: true
  tasks:
    - name: Install packages
      yum:
        name: 
          - httpd
          - mariadb
          - dhcpd
          - '@Development tools'
          - '*'
        state: latest 
