---
- name: Install httpd, mariadb, dhcpd, @Development tools and update the systems
  hosts: all
  become: true
  tasks:
    - name: Install packages
      yum:
        name: 
          - httpd
          - mariadb*
          - dhcp-server
          - '@Development tools'
          - '*'
        state: latest 
