---
- name: Manage VM power state
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - ../group_vars/all.yml
  roles:
    - role: proxmox_vm_power
